apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  destination:
    name: app
    namespace: app
    server: https://kubernetes.default.svc
  source:
    path: argo
    repoURL: https://github.com/external-Pritam-CoinDCX/demorepo.git
    targetRevision: HEAD
  sources: []
  project: default
