apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../app
- deploy.yml
# patches:
#   - target:
#       version: v1
#       kind: Deployment
#       name: nginx
#     patch: |-
#       - op: replace
#         path: /spec/replicas
#         value: 3